# Generated by Django 3.2.16 on 2022-11-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('presentacion', models.CharField(max_length=80)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
